### ISSUE TITLE
Prettier config out of date

### ISSUE THREAD

**Issue by wthueb** [creativenull/efmls-configs-nvim#104]
It seems like the prettier config might be out of date. The `--stdin` flag doesn't seem to be an option anymore with Prettier 3.1.0.

From `:LspLog`:
```
[ERROR][2023-11-17 16:46:59] .../vim/lsp/rpc.lua:675	"rpc"	"C:\\Users\\...\\AppData\\Local\\nvim-data\\mason\\bin\\efm-langserver.CMD"	"stderr"	"2023/11/17 16:46:59 C:\\Users\\...\\AppData\\Local\\nvim-data\\mason\\bin\\prettier.CMD --stdin --stdin-filepath '...'   --tab-width 4 : [warn] Ignored unknown option --stdin.\n[error] No parser could be inferred for file \"'...'\".\n\n"
```

**Comment by creativenull** [comment]
That (`--stdin`) looks like a warning and seems to be ignored by prettier, the error is the next line: `No parser could be inferred for file`.

Can you mention what file was it? (js, ts, etc)

**Comment by wthueb** [comment]
It was a .component.html file (Angular).

**Comment by creativenull** [comment]
You may have to manually change the parser option for html files to `angular` and see if that helps (inside your prettierrc): https://prettier.io/docs/en/configuration#setting-the-parserdocsenoptionshtmlparser-option

If you're still having problem, send me a repo project I can try out prettier in.

**Comment by wthueb** [comment]
> You may have to manually change the parser option for html files to `angular` and see if that helps (inside your prettierrc): https://prettier.io/docs/en/configuration#setting-the-parserdocsenoptionshtmlparser-option
> 
> 
> 
> If you're still having problem, send me a repo project I can try out prettier in.
> 
> 

That worked, strange since I didn't had to do that in previous Angular projects. Guess that's a Prettier issue rather than this repo though.

Thanks!
