### ISSUE TITLE
Not detailed enough output for flake8

### ISSUE THREAD

**Issue by ada0l** [creativenull/efmls-configs-nvim#11]
![Снимок экрана 2022-07-31 082207](https://user-images.githubusercontent.com/68809984/182002079-88ecf855-61f0-4744-a11b-1a619403120a.png)

```lua
local on_attach = function(client, bufnr)
    ...
end

local efmls = require('efmls-configs')
local black = require('efmls-configs.formatters.black')
local flake8 = require 'efmls-configs.linters.flake8'
efmls.init {
    on_attach = on_attach
}
efmls.setup {
    python = {
        linter = flake8,
        formatter =  black
    }
}

```

**Comment by creativenull** [comment]
Hmm not sure what happened there and I also stopped seeing the output as well.

Anyways this should be fixed, let me know if this works on your side.
