### ISSUE TITLE
sqlfluff linter config

### ISSUE THREAD

**Issue by Anthony-Fiddes** [creativenull/efmls-configs-nvim#110]
Hey @creativenull,

I noticed that you contributed a config for using `sqlfluff` as a linter on Reddit: https://www.reddit.com/r/neovim/comments/168vo47/how_to_integrate_sqlfluff_with_efmserver/.

Would you consider adding that config to this repo? I assume that maybe you had a good reason for not contributing it or that maybe you forgot about it. I've just been looking over different options for sql formatters and noticed this while I was browsing.

**Comment by creativenull** [comment]
Whoops I thought I did add this but guess I didn't get around to it 😅 

Thanks for pointing it out!

**Comment by Anthony-Fiddes** [comment]
Just commenting my gross config to have the command read from a .sqlfluff config file if it's available if it helps anyone:

```lua
local which_sqlfluff = fs.executable("sqlfluff")
-- I'd prefer that dialect was set from the nearest sqlfluff file
local sqlfluff_main_command =
  string.format("%s lint --format github-annotation-native --annotation-level warning --nocolor --disable-progress-bar ${INPUT}", which_sqlfluff)
-- If it fails default to ANSI
local sqlfluff_backup_command =
  string.format("%s lint --dialect ansi --format github-annotation-native --annotation-level warning --nocolor --disable-progress-bar ${INPUT}", which_sqlfluff)
local sqlfluff_command = string.format("%s || %s", sqlfluff_main_command, sqlfluff_backup_command)
sqlfluff = vim.tbl_extend("force", sqlfluff, { lintCommand = sqlfluff_command })
```
