### ISSUE TITLE
how to config the swiftformat for efmls? I can't understand different formatter configuration in source code.

### ISSUE THREAD

**Issue by 0xnofoot** [creativenull/efmls-configs-nvim#115]

**Comment by 0xnofoot** [comment]
I do it, use this command: "swiftformat stdin --stdinpath '${INPUT}'"
local ls = {
	sh = {
		require('efmls-configs.formatters.beautysh'),
	},
	zsh = {
		require('efmls-configs.formatters.beautysh'),
	},

	swift = {
		{
			formatCommand = "swiftformat stdin --stdinpath '${INPUT}'",
			formatStdin = true,
		}
	}
}

L = {
	setup = function(lspconfig)
		lspconfig.efm.setup({
			filetypes = vim.tbl_keys(ls),

			init_options = {
				documentFormatting = true,
				documentRangeFormatting = true,
			},

			settings = {
				languages = ls,
			},
		})
	end,
}

return L

**Comment by creativenull** [comment]
I think you are missing `--quiet` but I've went ahead and added the swiftformat as a config for you to try.

Try to update the plugin and replace your swift with the following:

```lua
local ls = {
  -- ...
  swift = {
    require('efmls-configs.formatters.swiftformat')
  }
}
```

Let me know if you're still having issues with the config or not.

**Comment by 0xnofoot** [comment]
thank you very much, there will be error in LspLog without --quiet, thank you for your comment and update.

I have other problem for realm/SwiftLint, I tried my best but couldn't configure it, so I ended up using nvim-lint.
Could you give me some advice if you have time? Finally, thank you again for your update, which is very helpful to me.

**Comment by creativenull** [comment]
Added `swiftlint`, give it try whenever you can or anyone else. 

Also feel free to look at the code and use it however you want. I've tested it on my machine and seems like the `lintFormats` work.
