### ISSUE TITLE
Unclear how to partially override `efmls-configs`

### ISSUE THREAD

**Issue by savchenko** [creativenull/efmls-configs-nvim#121]
For example, I want to incorporate the following:

```lua
languages = {
    bash = {
        { formatCommand = "shfmt -i 2 -bn -kp", formatStdin = true }
    }
```

How do I correctly integrate it in:

```lua
local shellcheck = require('efmls-configs.linters.shellcheck')
local shfmt = require('efmls-configs.formatters.shfmt')
local languages = {
    bash = { shfmt, shellcheck },
}
```

**P.S.** Perhaps enable the "discussions" module at GitHub for issues like this one?

**Comment by creativenull** [comment]
Hmm I might have to document this more clearly then, I already had a small hint over in the [Default Configurations](https://github.com/creativenull/efmls-configs-nvim?tab=readme-ov-file#default-configurations) section.

But to override you should use the builtin `vim.tbl_extend()` (`:help vim.tbl_extend`) function to extend a lua table.

For your example:

```lua
local shfmt = require('efmls-configs.formatters.shfmt')
shfmt = vim.tbl_extend('force', shfmt, {
  -- Override any key in here
  formatCommand = "shfmt -i 2 -bn -kp",
  formatStdin = true,
})
```
