### ISSUE TITLE
ERROR "mcs": No global executable found, check |efmls-configs-issues| for help

### ISSUE THREAD

**Issue by princenizroh** [creativenull/efmls-configs-nvim#129]
Why my :checkhealth show this ERROR 
On mason I have installed it is omnisharp, omnisharp-mono, csharpier, csharp-language-server and that's not worked
![240331_07h46m35s_screenshot](https://github.com/creativenull/efmls-configs-nvim/assets/113965138/74671ffb-d1d3-4d40-b4c1-a9707c0b499e)
![image](https://github.com/creativenull/efmls-configs-nvim/assets/113965138/967fec71-6811-47ba-a138-09f68ca8553f)
![image](https://github.com/creativenull/efmls-configs-nvim/assets/113965138/820c631c-dac9-4bc4-acee-8315eb9b5e36)

**Comment by creativenull** [comment]
Hey, correct me if I'm wrong but `mcs` comes builtin with the C# compiler no? Maybe the compiler is not added to your global paths.

I don't think mason provides it by default, since mason only provides you with C# LSP servers (built by community) and/or other tools that do not come builtin on the compiler.

Can you verify if you see `mcs` listed in the mason bin directory? For you that should be `~/.local/share/nvim/mason/bin`

**Comment by creativenull** [comment]
That is weird, according to the the arch linux docs `mcs` should come installed when you install `mono`. I'm looking at this link: https://wiki.archlinux.org/title/Mono

> Of course, such as omnisharp, omnisharp-mono, csharp-ls are already installed. It's just that mcs doesn't detect that lsp on mason. So does MCS really not support the LSP available on Mason?

Just to re-iterate `mcs` has nothing to do with what you installed using Mason.nvim nor is it LSP. It's just part of the mono toolchain, so when you install mono you should be getting `mcs` with it too.

I don't have an arch system so I cannot test this out, but I did try it out on my ubuntu system and installing `mono` did indeed come with `mcs`.

![image](https://github.com/creativenull/efmls-configs-nvim/assets/3767728/f51ed516-3643-433b-b544-d47841ae59fe)


You may have to try rebuilding/reinstalling mono on your system and check if `mcs` is present with a `which mcs` in the terminal.

**Comment by princenizroh** [comment]
Yeah same your location mono and mcs

**Comment by princenizroh** [comment]
Are you testing mcs lsp? I want to see it

**Comment by creativenull** [comment]
If your mono and mcs is already globally available then I'm not exactly sure why it's not picking it up in your config.

From my testing it should be working on a linux machine once globally available, maybe something in your config is blocking it somehow, which I cannot tell. I'm afraid you'll have to find out what is the problem on your machine.

Anyway, here is a quick video on my test case (couldn't upload to github cuz file is 40mb)

https://streamable.com/gdjhow

**Comment by princenizroh** [comment]
Thank you for show it. I don't know why that is. Maybe i will test with a different distro like debian beside arch. 
Here I put efmls-config https://github.com/princenizroh/dotprofiles-linux/blob/main/.config/nvim/lua/princenizroh/plugins/nvim-lspconfig.lua

**Comment by creativenull** [comment]
I see that `cs = { mcs, dotnet_format }` entry is not there in languages (https://github.com/princenizroh/dotprofiles-linux/blob/3ab9c8ec1c4de0ba465788f890bd2bb6aa1c7a4f/.config/nvim/lua/princenizroh/plugins/nvim-lspconfig.lua#L253)

That is how nvim filetype is defined for C# files using the `cs` filetype.

But I tried out your config and looks like mcs is detected for me:

![Screenshot from 2024-04-16 17-57-03](https://github.com/creativenull/efmls-configs-nvim/assets/3767728/a1eecfa0-910f-4e2f-8e4c-6287ae04ca5c)

**Comment by creativenull** [comment]
Closing this for now, let me know if you were able to resolve or still having the same issue.

**Comment by princenizroh** [comment]
still not resolved, nvm i will close it
