### ISSUE TITLE
Sqlfluff linting does not seem to work

### ISSUE THREAD

**Issue by Uaitt** [creativenull/efmls-configs-nvim#134]
Hello :)

This is my current efm config:
```lua
lspconfig.efm.setup(require("lsp.settings.efm"))

-- in lsp/settings/efm.lua
local sqlfluff = require("efmls-configs.linters.sqlfluff")

return {
  filetypes = {
    "sql",
  },
  init_options = {
    documentFormatting = true,
    documentRangeFormatting = true,
    hover = true,
    documentSymbol = true,
    codeAction = true,
    completion = true,
  },
  settings = {
      sql = { sqlfluff },
    },
  },
}
```
which seems correct because all the other linters/formatted that I have attacched (and omitted in the previous snippet) work correctly.

This is a file that contains offenses:

![Screenshot from 2024-05-05 14-06-44](https://github.com/creativenull/efmls-configs-nvim/assets/97030518/875e2e69-29d7-4b68-94a2-4a00a5bbf7b3)

As you see, efm does not report anything on my editor.

However, if I try to run the linter manually, with the flags specified in the config from this repo the warnings are reported.
![Screenshot from 2024-05-05 14-08-55](https://github.com/creativenull/efmls-configs-nvim/assets/97030518/4a356a2e-7e3d-4a45-8c33-c47fdd026e69)

Is there something that I am missing here?

**Comment by creativenull** [comment]
Seems like the a new sqlfluff update added a `endLine` and `endColumn` options to the errors.

I've updated the format to pick those up, please update the plugin and let me know if you are still having issues or not.

Ref: https://github.com/creativenull/efmls-configs-nvim/commit/51cb9191aa2776477e2e75180f9a466f0efaac43

**Comment by Uaitt** [comment]
@creativenull Works like a charm now!
![Screenshot 2024-05-07 at 11 04 32](https://github.com/creativenull/efmls-configs-nvim/assets/97030518/12229c36-0cb6-479b-b3a9-9576229eaecc)
Is there any chance you could add support for [formatting](https://docs.sqlfluff.com/en/stable/cli.html#sqlfluff-format) via sqlfluff?

**Comment by creativenull** [comment]
Done :)

Ref: https://github.com/creativenull/efmls-configs-nvim/commit/f477186ecc12ac025a9948d17edc69242e1ee96b

However note that, you will have to follow issue #87 if you want to see it format properly, becuase efm can only take changes from stdout - which sqlfluff does not and directly changes the file in the filesystem.

**Comment by Uaitt** [comment]
@creativenull thanks, I have managed to make the formatter work too :)! I think you can close this issue now.
