### ISSUE TITLE
docs/usage: `lspconfig.setup` directly?

### ISSUE THREAD

**Issue by llllvvuu** [creativenull/efmls-configs-nvim#16]
Is it possible to do directly?

```lua
require "lspconfig".efm.setup {
    init_options = {documentFormatting = true},
    settings = {
        rootMarkers = {".git/"},
        languages = {
            lua = {
                require('efmls-configs.linters.luacheck'),
                require('efmls-configs.formatters.stylua'),
            }
        }
    }
}
```

This way no need to go indirectly through `efmls-configs-nvim` setup API

**Comment by creativenull** [comment]
At this point not really, there is one option that we have called `default_config` which will load a list of predefined linters and formatters listed in [default configurations](https://github.com/creativenull/efmls-configs-nvim/blob/main/supported-linters-and-formatters.md#default-configurations)

I can move it to a function that lspconfig can consume with

```lua
require "lspconfig".efm.setup {
    init_options = {documentFormatting = true},
    settings = {
        rootMarkers = {".git/"},
        languages = require "efmls-configs".default_languages
    }
}

But will require some changes to how it's being handled
```

**Comment by creativenull** [comment]
At this point not really, there is one option that we have called `default_config` which will load a list of predefined linters and formatters listed in [default configurations](https://github.com/creativenull/efmls-configs-nvim/blob/main/supported-linters-and-formatters.md#default-configurations) page.

I can move it to a function that lspconfig can consume with:

```lua
require "lspconfig".efm.setup {
    init_options = {documentFormatting = true},
    settings = {
        rootMarkers = {".git/"},
        languages = require "efmls-configs".default_languages
    }
}
```

Initially the way I wrote it was for my [diagnosticls-configs](https://github.com/creativenull/diagnosticls-configs-nvim) plugin and was wanting to simplify the same interface into this plugin.

But open for some suggestions!

**Comment by llllvvuu** [comment]
> require "efmls-configs".default_languages

This makes a lot of sense! Works nicely with `tbl_extend` / `tbl_deep_extend`. Probably can already use `require "efmls-configs/defaults"`. Just a matter of pointing it out in the README if it works I think. I'll try it in my own config sometime when I get the chance.

**Comment by creativenull** [comment]
Thinking of the following ways to setup (adding them here for reference):

### Method 1 - Standalone

```lua
-- Setup a list of default linters/formatters to run with efm
local languages = require('efmls-configs').default_languages

require('lspconfig').efm.setup({
  filetypes = vim.tbl_keys(languages),
  settings = {
    rootMarkers = { '.git/' },
    languages = languages,
  },
  
  on_attach = ...,
  capabilities = ...,
  init_options = {
    documentFormatting = true,
    documentRangeFormatting = true,
  },
})
```

Languages can also be defined as a custom table if you don't want all the default ones:

```lua
-- Define a custom configuration
local languages = {
  typescript = {
    require('efmls-configs.linter.eslint'),
    require('efmls-configs.formatters.prettier'),
  },
  lua = {
    require('efmls-configs.linter.luacheck'),
  },
}
```

### Method 2 - with a `setup()` API

However I wanted to make a simple API for my usecase, which is optional.

```lua
local efm_config = require('efmls-configs').setup({
  -- Setup a list of default linters/formatters to run with efm
  defaults = true,
  
  -- Define a custom configuration
  -- Also overrides any language defined in `defaults`
  -- `linters`/`formatters` take a string or a table
  languages = {
    typescript = {
      linters = {
        'eslint',
        require('efmls-configs.linters.xo'),
      },
      formatters = { 'prettier' },
    },
    lua = {
      linters = { 'luacheck' },
    },
  },
})

require('lspconfig').efm.setup(vim.tbl_extend('force', efm_config, {
  on_attach = ...,
  capabilities = ...,
  
  -- Below will be automatically included from `setup()`
  -- init_options = {
  --   documentFormatting = true,
  --   documentRangeFormatting = true,
  -- },
}))
```

**Comment by creativenull** [comment]
Referencing this PR for relevance: #30

**Comment by llllvvuu** [comment]
Amazing!
