### ISSUE TITLE
cannot find global node executable if NVM is used

### ISSUE THREAD

**Issue by lucax88x** [creativenull/efmls-configs-nvim#2]
So, I'm using NVM, which is a node version manager that allows me to use different node versions.

my globals are installed in a path like 

/home/lucatrazzi/.nvm/versions/node/v16.2.0/bin/eslint_d

using

```lua
:lua print(vim.fn.exepath('eslint_d')) 
```

returns me the correct path so I don't know what is doing wrong

ps: only node globals are giving me issues, the others like stylelua or shfmt works perfect.

**Comment by lucax88x** [comment]
looking at code

https://github.com/creativenull/efmls-configs-nvim/blob/main/lua/efmls-configs/fs.lua#L61

get_local_exec ALWAYS return a string, so it will never check for globals, am I wrong?

inside get_local_exec if filereadable is === 0 you should put binpath to nil so you effectively return a nil binpath and then check for global, no?

**Comment by creativenull** [comment]
Hey, yes you're right it won't get the global bin path even if it fails.

Good catch I'll review the PR 👍

**Comment by creativenull** [comment]
Merged #4 

Can you verify if you are still getting the issue after update? I've tried on my end and don't see any issue after update

**Comment by lucax88x** [comment]
Nope, it works perfectly! Thanks!
