### ISSUE TITLE
prettier_d fails `:healthcheck` because `prettier` cannot be found.

### ISSUE THREAD

**Issue by j-barnak** [creativenull/efmls-configs-nvim#51]
When using 

```
require("efmls-configs.formatters.prettier_d"),
```

with 

```
local languages = {
  javascript = {
    require("efmls-configs.formatters.prettier_d"),
  },
}
```

I'll fail `:checkhealth` with an error because the `prettier` executable cannot be found.

```
efmls-configs: require("efmls-configs.health").check()

- ERROR "prettier": no executable found, check |efmls-configs-issues| for help
```

Shouldn't it be looking for the `prettierd` executable?

**Comment by creativenull** [comment]
That's because the `rootMarkers` were coming from the prettier config. `prettierd` should work if you don't see the error on `:checkhealth`

Will fix it to have it just use hard coded `rootMarkers` instead.
