### ISSUE TITLE
how to create a new config

### ISSUE THREAD

**Issue by endir** [creativenull/efmls-configs-nvim#53]
Hello, 
thank you for the great work! 
I think it would be helpful to have some documentation on how to create a new linter/formatter config.

For example, I have some small custom "linter" scripts that take a filename name as arg and output some diagnostics. E.g.
$ linter_name fname 
1:1:some error

where the output has the convention %l:%c:%m. Just for the sake of making it as simple as possible, lets assume that the linter is
#include <iostream>
#include <fstream>
using namespace std;

int main(){
  cout << "1:1:this is a message"<<endl;
  // cout << "1:1:this is a message";
  ofstream myfile;
  myfile.open("/tmp/log_file");
  myfile << "done" << endl;
  myfile.close();
  return 0;
}

Suppose that the above is compiled to /tmp/a.out

If I use

local fs = require('efmls-configs.fs')
local linter = '/tmp/a.out'
local command = string.format('%s', fs.executable(linter, fs.Scope.NODE))

return {
  prefix = linter,
  lintCommand = command,
  lintStdin = false,
  lintFormats = { "%l:%c:%m"},
}

**Comment by endir** [comment]
sorry for some reason the message was not pasted completely. 
If I use

local fs = require('efmls-configs.fs')
local linter = '/tmp/a.out'
local command = string.format('%s', fs.executable(linter, fs.Scope.NODE))

return {
prefix = linter,
lintCommand = command,
lintStdin = false,
lintFormats = { "%l:%c:%m"},
}

I can see that the program executed by efm but the linter diagnostics are not present in neovim. 

What am I doing wrong?

**Comment by endir** [comment]
This is what I am trying

local fs = require('efmls-configs.fs')
local linter = 'test_linter'

return {
  prefix = linter,
  lintCommand = '/tmp/a.out',
  lintStdin = false,
  lintFormats = { "%l:%c:%m"},
}

**Comment by creativenull** [comment]
What file are you trying this on? It won't work if you don't specify a filetype when you setup efm.

Also it would help to check `:LspLog` with debug mode enabled `vim.lsp.set_log_level('DEBUG')`

**Comment by creativenull** [comment]
Closing this for now as it is not something that's planned for this plugin.
