### ISSUE TITLE
Generate machine-readable list of tools

### ISSUE THREAD

**Issue by traxys** [creativenull/efmls-configs-nvim#61]
Would it be possible to generate a machine readable list of tools in addition to the markdown documentation ? 

I help maintain a project called [nixvim](https://github.com/nix-community/nixvim) that maps neovim lua configurations to nix, and to support nicely this plugin we extract from the files the metadata and export it to json ([exporter](https://github.com/nix-community/nixvim/blob/main/helpers/efmls-configs/extract.py) and [metadata](https://github.com/nix-community/nixvim/blob/main/plugins/lsp/language-servers/efmls-configs-tools.json)).

This is a bit brittle, because the tool could break at any time due to upstream changes, and as there already is a generator could it be possible to add a json (or other format) document that lists all the available tools ?

**Comment by creativenull** [comment]
Correct me if I'm wrong, you would like a json file detailing all the linters and formatters associated to a language?

Something similar to the [defaults.json file](https://github.com/creativenull/efmls-configs-nvim/blob/main/lua/efmls-configs/defaults.json) but just for all languages?

**Comment by traxys** [comment]
Exactly!

**Comment by traxys** [comment]
It could be ordered by tool, or by language, it only needs to be exhaustive & machine readable, then anything can be done with it! (by language would be the simplest)

**Comment by creativenull** [comment]
Hmm yeah I think its a nice idea, I could just make it the same as the defaults file 🤔

**Comment by creativenull** [comment]
@traxys let me know if this will be enough for your nix generation, or if there are some improvements needed.

**Comment by traxys** [comment]
I think it should be enough, I'll implement the mapping from JSON to nix and tell you how it went!

**Comment by traxys** [comment]
I implemented the nix generation, it worked fine!

**Comment by creativenull** [comment]
Nice!
