### ISSUE TITLE
Bug: `formatStdin = false` is being ignored

### ISSUE THREAD

**Issue by chrisgrieser** [creativenull/efmls-configs-nvim#64]
So I was trying to add some more formatters (which I'll happily add via PR, too, when I get them working), however I hit a roadblock with formatters that do not read from stdin.

`codespell`, for instance, can be used as a formatter to automatically fix misspellings across the whole buffer. This command works for that:

```bash
codespell --write-changes foobar.lua
```

However, when I try to set up the respective efm-config, it appears that `formatStdin = false,` is being ignored; instead the whole buffer is overwritten with codespell's stdout (which in this case is an empty string):

```lua
local fs = require("efmls-configs.fs")

local formatter = "codespell"
local args = "--write-changes ${INPUT}"
local command = string.format("%s %s", fs.executable(formatter), args)

return {
	formatCommand = command,
	formatStdin = false,
}
```

I tried other formatters with `formatStdin = false`, and it appears they share that issue. Or am I missing something here?

**Comment by davidosomething** [comment]
it's an efm issue https://github.com/mattn/efm-langserver/issues/258

**Comment by chrisgrieser** [comment]
I see. Will subscribe to that issue then and close this, since it's an upstream problem.
