### ISSUE TITLE
[feature request] Exclude langs completely from default without `:checkhealth` complaining.

### ISSUE THREAD

**Issue by Lazerbeak12345** [creativenull/efmls-configs-nvim#77]
I'd like to use `require'efmls-configs.defaults'.languages()`, but there are a few languages I know I don't need.

My approach has been something like this:

```lua
local function efm_formatter(name)
	return require("efmls-configs.formatters." .. name)
end
local function efm_linter(name)
	return require("efmls-configs.linters." .. name)
end
local default_langs = require"efmls-configs.defaults".languages()
default_langs.python = nil
default_langs.php = nil
default_langs.nix = nil
default_langs.blade = nil
require'lspconfig'.efm.setup{
	on_attach = default_args.on_attach,
	capabilities = capabilities,
	settings = {
		rootMarkers = {".git/"},
		languages = vim.tbl_extend("force", default_langs, {
			rust = { efm_formatter"rustfmt" },
			-- We want both luacheck and selene.
			lua = vim.tbl_extend("keep", default_langs.lua, { efm_linter"selene" }),
			sh = { efm_formatter"shellharden" },
			fish = { efm_linter"fish", efm_formatter"fish_indent" }
		})
	}
}
```

But the problem is that this plugin seems to be checking for the executables at call-time of the `languages` function, so these tools (which aren't installed) are warned in the health check as being absent.

Perhaps some sort of argument could be given to not include a language? I'm not really sure.

Aside: It's totally fine if the answer is just "don't use the defaults".

**Comment by Lazerbeak12345** [comment]
Oh, here's the checkhealth output (with the above)

```
- ERROR "alejandra": no executable found, check |efmls-configs-issues| for help
- ERROR "": no executable found, check |efmls-configs-issues| for help
- ERROR "phpcs": no executable found, check |efmls-configs-issues| for help
- ERROR "phpcbf": no executable found, check |efmls-configs-issues| for help
- ERROR "flake8": no executable found, check |efmls-configs-issues| for help
- ERROR "autopep8": no executable found, check |efmls-configs-issues| for help
- ERROR "blade-formatter": no executable found, check |efmls-configs-issues| for help
```

**Comment by Lazerbeak12345** [comment]
Sorry for bothering you... not using the defaults is much less code. The only real problem here might be that `- ERROR "": no executable found, check |efmls-configs-issues| for help` line.

**Comment by creativenull** [comment]
That empty one is worth looking at separately, but yes it's best to just use the ones you'd like. And if you are using defaults then it's perfectly fine to ignore the errors in `:checkhealth`. Maybe `ERROR` is too scary can change it to `WARNING` instead 🤔
