### ISSUE TITLE
clang format deletes changes on write

### ISSUE THREAD

**Issue by lsig** [creativenull/efmls-configs-nvim#81]
Hi and thanks for this plugin I have setup up efm and used your configs for setting up my linters and formatters. 

Whenever I save/write a cpp file and a c file the changes, instead of being formatted, are removed for some reason. I was wondering if you know what might be causing this behaviour since I have not specifically configured clang_format on my end, just downloaded it through Mason. When I used clang_format with null-ls this did not happen. 

Here is my config: 
```
local prettier = require("efmls-configs.formatters.prettier")
local eslint_d = require("efmls-configs.linters.eslint_d")
local clang_format = require("efmls-configs.formatters.clang_format")
local black = require("efmls-configs.formatters.black")
local stylua = require("efmls-configs.formatters.stylua")
local golangci_lint = require("efmls-configs.linters.golangci_lint")
local gofmt = require("efmls-configs.formatters.gofmt")

local languages = {
	typescript = { eslint_d, prettier },
	typescriptreact = { eslint_d, prettier },
	javascript = { eslint_d, prettier },
	javascriptreact = { eslint_d, prettier },
	json = { prettier },
	html = { prettier },
	cpp = { clang_format },
	c = { clang_format },
	python = { black },
	lua = { stylua },
	go = { golangci_lint, gofmt },
}
```
and where I setup efm
```
require("lspconfig").efm.setup({
	init_options = {
		documentFormatting = true,
		documentRangeFormatting = true,
	},
	filetypes = vim.tbl_keys(languages),
	settings = {
		rootMarkers = { ".git/", "package.json" },
		languages = languages,
	},
	capabilities = capabilities,
	on_attach = on_attach,
})
```
Formatting setup (inside on_attach): 
```
if current_client.supports_method("textDocument/formatting") then
		vim.api.nvim_create_autocmd("BufWritePre", {
			group = augroup,
			buffer = bufnr,
			callback = function()
				lsp_formatting(bufnr)
			end,
		})
	end
```
lsp_formatting function: 
```
local augroup = vim.api.nvim_create_augroup("LspFormatting", { clear = true })

local lsp_formatting = function(bufnr)
	vim.lsp.buf.format({
		filter = function(client)
			return client.name == "efm"
		end,
		bufnr = bufnr,
	})
end
```
Thanks in advance 💯

**Comment by creativenull** [comment]
Can you disable the autocmd (inside your on_attach) and try to format manually via `:lua vim.lsp.buf.format()` and see if you get the same problem?

**Comment by lsig** [comment]
If I run vim.lsp.buf.format() after disabling the autocommand it works, but isn't that just because then neovim using clangd to format the file instead of efm specifically or am I misunderstanding?

**Comment by creativenull** [comment]
If you have other lsp servers running in addition to efm then neovim will run the format command for all the servers, so it will run the format from those servers and then it will run the format from efm, depends on the order you setup them up in your config.

Looks like there is nothing wrong with the formatting, my suspicion is that autocmd hasn't been setup properly.

Can you try to register this autocmd outside of on_attach?

I don't have a format on save in my config so this is something user-related and not this plugin. But here is how I would register an autocmd outside on_attach so it would only be triggered if you have `efm` running in a project (not tested).

```lua
local lsp_group = vim.api.nvim_create_augroup('LspFormattingGroup', {})
vim.api.nvim_create_autocmd('BufWritePost', {
  group = lsp_group,
  callback = function()
    local efm = vim.lsp.get_active_clients({ name = 'efm' })

    if vim.tbl_isempty(efm) then
      return
    end

    vim.lsp.buf.format({ name = 'efm' })
  end,
})
```

Else you can try [lukas-reineke/lsp-format.nvim](https://github.com/lukas-reineke/lsp-format.nvim) and see if that helps with the format on save.

**Comment by lsig** [comment]
Yeah I definitely set up my autocmd wrong, your suggestion worked perfectly. I did not expect it to be the autocmd, because it worked with other formatters, but any how thank you so much for your help 💯
