### ISSUE TITLE
[Question|Help] Why my stylua is not working?

### ISSUE THREAD

**Issue by kassio** [creativenull/efmls-configs-nvim#82]
My lsp config is:

```lua
local lspconfig = require('lspconfig')
local capabilities = require('plugins.lsp.capabilities')

local servers = {
  bashls = {},
  cssls = {},
  efm = require('plugins.lsp.servers.efm'),
  gopls = require('plugins.lsp.servers.gopls'),
  jqls = {},
  jsonls = {},
  jsonnet_ls = {},
  lua_ls = require('plugins.lsp.servers.lua_ls'),
  solargraph = require('plugins.lsp.servers.solargraph'),
  sqlls = {},
  yamlls = require('plugins.lsp.servers.yamlls'),
}

for server, opts in pairs(servers) do
  local config = vim.tbl_deep_extend('force', opts or {}, {
    single_file_support = true,
    capabilities = capabilities,
  })

  lspconfig[server].setup(config)
end
```

where, `plugins.lsp.servers.efm` is:

```lua
local languages = {
  lua = {
    require('efmls-configs.formatters.stylua'),
  },
  go = {
    require('efmls-configs.linters.golangci_lint'),
  },
  ruby = {
    require('plugins.lsp.servers.efm.rubocop'),
  },
  sh = {
    require('efmls-configs.formatters.shfmt'),
    require('efmls-configs.linters.shellcheck'),
  },
}

return {
  filetypes = vim.tbl_keys(languages),
  settings = {
    logLevel = vim.lsp.log_levels.ERROR,
    logFile = vim.lsp.get_log_path(),
    languages = languages,
  },
  init_options = {
    codeAction = true,
    completion = true,
    documentFormatting = true,
    documentRangeFormatting = true,
    documentSymbol = true,
    hover = true,
  },
}
```

I tried many different things, but can't find a reason why lua is not getting formatted. :/

I keep getting: `INFO [LSP] Format request failed, no matching language servers.`

Help?

**Comment by creativenull** [comment]
Please refer to the setup guide and see what you are missing: https://github.com/creativenull/efmls-configs-nvim?tab=readme-ov-file#setup

Looks like you didn't include `rootMarkers` inside your `settings` within `lua/plugins/lsp/servers/efm.lua` file. This is needed so that efm can attach and run the formatter.

**Comment by kassio** [comment]
Thanks @creativenull!

Unfortunately it didn't fix.

```lua
return {
  filetypes = vim.tbl_keys(languages),
  init_options = {
    codeAction = true,
    completion = true,
    documentFormatting = true,
    documentRangeFormatting = true,
    documentSymbol = true,
    hover = true,
  },
  settings = {
    logLevel = vim.lsp.log_levels.ERROR,
    logFile = vim.lsp.get_log_path(),
    languages = languages,
  rootMarkers = { '.git/' }
  },
}
```
---

Also, I know it's on the efm repo, but this is not marked as required in the [schema](https://github.com/mattn/efm-langserver/blob/master/schema.md#5-property-root-markers) 😞

**Comment by creativenull** [comment]
Check if you are able to format using `:lua vim.lsp.buf.format({ name = 'efm' })`

**Comment by kassio** [comment]
@creativenull, yes, that worked!

But the autocommand doesn't! 🤔 

```lua
      vim.api.nvim_create_autocmd({'BufWritePre'}, {
        callback = function()
          if not vim.bo.modifiable or vim.b.skip_autoformat == true then
            return
          end

          vim.lsp.buf.format()
        end,
      })
```

**Comment by kassio** [comment]
If I add `{name = 'efm'}` on the autocommand it also works. It seems that somehow it's not associating the lsp with the filetype?

**Comment by kassio** [comment]
<img width="416" alt="image" src="https://github.com/creativenull/efmls-configs-nvim/assets/120483/795582bf-80d7-49b1-9dd3-27e2be77eb7b">

**Comment by creativenull** [comment]
I'm guessing it has to do with `lua_ls` not having a format feature so it just stops there. But it is supposed to just fail gracefully and then move onto the next server to issue the format command.

You can try out the autocmd code I did in another issue (https://github.com/creativenull/efmls-configs-nvim/issues/81#issuecomment-1722533616) this is registered separately and not inside an on_attach etc. Or try an alternative for formatting: [lukas-reineke/lsp-format.nvim](https://github.com/lukas-reineke/lsp-format.nvim)

**Comment by kassio** [comment]
Thanks @creativenull.

I just did a little adjustment on that and it worked perfectly. 

```lua
      vim.api.nvim_create_autocmd({'BufWritePre'}, {
        callback = function()
          if not vim.bo.modifiable or vim.b.skip_autoformat == true then
            return
          end

          local efm = vim.lsp.get_clients({ name = 'efm' })

          if vim.tbl_isempty(efm) then
            vim.lsp.buf.format()
          else
            vim.lsp.buf.format({ name = 'efm' })
          end
        end,
      })
```
