### ISSUE TITLE
:checkhealth makes the plugin look broken

### ISSUE THREAD

**Issue by RoryNesbitt** [creativenull/efmls-configs-nvim#86]
When you run checkhealth efm-ls.nvim only shows errors, the oks are hidden

If you show `OK "stylua": V1.0` etc it will give the happy feelings

Also if the executables aren't required for the plugin to function (e.g. `phpcs` shouldn't be needed when working in lua) then imo it should be a warning not an error

**Comment by creativenull** [comment]
I will look into showing OK messages for tools that are in your system.
