### ISSUE TITLE
Formatter does not reflect changes to the buffer

### ISSUE THREAD

**Issue by creativenull** [creativenull/efmls-configs-nvim#87]
## Problem

If you ran any formatter that [does not take a `stdin`](https://github.com/search?q=repo%3Acreativenull%2Fefmls-configs-nvim%20formatStdin%20%3D%20false&type=code) (Also see #78 and  #64) then you will run into problems where you won't see your formatted code changes.

The unfortunate part is that you will have to save the file and then run `:edit!` to see those changes, since those formatters will only work on files saved on the system.

## Solution

One solution would be to run the format command after save, for example ([for a better version see the last code block](\#final-solution-code)):

```lua
local function efm_fmt(buf)
  local matched_clients = vim.lsp.get_active_clients({ name = 'efm', bufnr = buf })

  if vim.tbl_isempty(matched_clients) then
    return
  end

  local win_state = vim.call('winsaveview')

  vim.lsp.buf.format({ name = 'efm' })

  vim.cmd('silent edit!')
  vim.call('winrestview', win_state)
end
```

You will need `winsaveview()` and `winrestview()` so that the cursor and window position is saved before formatting the file. `silent` is needed so it does not error if it fails, we want to handle it gracefully.

Add this to your `on_attach`:

```lua
local function on_attach(client, buf)
  vim.keymap.set('n', '<Leader>lf', function() efm_fmt(buf) end, { buffer = buf, desc = 'Format the buffer' })

  -- ...
end
```

Or to your autocmd to format on save:

```lua
local lsp_fmt_group = vim.api.nvim_create_augroup('LspFormattingGroup', {})
vim.api.nvim_create_autocmd('BufWritePost', {
  group = lsp_fmt_group,
  callback = function(ev)
    efm_fmt(ev.buf)
  end,
})
```

### Final Solution Code

We can take this one step further and account for when a formatter has `formatStdin = false` and only call `:edit!` or just format as is.

```lua
local function fmt_with_edit()
  local win_state = vim.call('winsaveview')

  vim.lsp.buf.format({ name = 'efm' })

  vim.cmd('edit!')
  vim.call('winrestview', win_state)
end

local function efm_fmt(buf)
  local matched_clients = vim.lsp.get_active_clients({ name = 'efm', bufnr = buf })

  if vim.tbl_isempty(matched_clients) then
    return
  end

  local efm = matched_clients[1]
  local ft = vim.api.nvim_buf_get_option(buf, 'filetype')
  local formatters = efm.config.settings.languages[ft]

  local matches = vim.tbl_filter(function(fmt)
    return not fmt.formatStdin
  end, formatters)

  if not vim.tbl_isempty(matches) then
    fmt_with_edit()
  else
    vim.lsp.buf.format({ name = 'efm' })
  end
end
```

**Comment by creativenull** [comment]
Anyone is free to provide any tips on this should it need modification!

**Comment by Uaitt** [comment]
If you are using an [auto-save plugin](https://github.com/pocco81/auto-save.nvim) and you want to format the current buffer with a formatter that does not take stdin input, you can try this approach:
```lua
local function efm_fmt_with_auto_save()
  -- check if efm is available in the current buffer

  vim.lsp.buf.format({ name = "efm", async = false })
  vim.api.nvim_feedkeys("n", "n", true)
  vim.api.nvim_feedkeys("<CR>", "n", true)
  vim.cmd("edit!")
end
```

Hope this helps somebody 😃.
