### ISSUE TITLE
Any interest in merging support for sql-formatter?

### ISSUE THREAD

**Issue by Anthony-Fiddes** [creativenull/efmls-configs-nvim#88]
Hey all! I love using efmls-configs, and I recently used it to add support for sql-formatter in my editor. The code is very simple and I was wondering if you would be interested in me opening a PR to contribute the change (obviously I would run the formatter with the repo's stylua and review the contributing guidelines).

The one thing I thought might be odd/nonstandard is how I added support for configuring the tool with a JSON file in the std config path. If there's a better way to accomplish that I'm definitely open to feedback.

Here's the snippet: 

``` lua
-- Metadata
-- languages: sql
-- url: https://github.com/sql-formatter-org/sql-formatter

local fs = require("efmls-configs.fs")
local ok, Path = pcall(require, "plenary.path")

local args = ""
if ok then
  local cfg = Path:new(vim.fn.stdpath("config"), "sql-formatter.json")
  if cfg:exists() and cfg:is_file() then
    args = string.format("--config %s", cfg)
  end
end

local formatter = "sql-formatter"

local command = string.format("%s %s", fs.executable(formatter, fs.Scope.NODE), args)

return {
  formatCommand = command,
  formatStdin = true,
}
```

**Comment by creativenull** [comment]
Of course! PRs are always welcome :)

**Comment by creativenull** [comment]
Will you be making this PR or you don't mind me or someone else do it?

**Comment by Anthony-Fiddes** [comment]
Sorry for the delay, I was actually just working on it. Should be up soon. Thanks for checking in with me :)

**Comment by Anthony-Fiddes** [comment]
Added #90!

**Comment by creativenull** [comment]
Check this comment if you want to use a custom config file for `sql-formatter`: https://github.com/creativenull/efmls-configs-nvim/pull/90#issuecomment-1746001139
