### ISSUE TITLE
Feature request: Use mason-installed, non pip/node executables when available

### ISSUE THREAD

**Issue by Anthony-Fiddes** [creativenull/efmls-configs-nvim#92]
Would it be possible/advisable to add the functionality to fs to use mason-installed executables? I assume we could just look in the default mason install location to see if the executable exists there. I'd be happy to give it a try if you think it's a good idea!

**Comment by creativenull** [comment]
This should work out of box from my understanding. Does it not work if you install a tool from mason and it not being picked up by this plugin?

**Comment by Anthony-Fiddes** [comment]
Specifically I'm experiencing the issue with stylua. I ended up having to run `cargo install stylua` to get formatting with it to work. The plugin works very well with mason-installed node and pip dependencies, so I am now realizing how confusing my issue title was.

When I :LspLog I get the following

```
[ERROR][2023-10-06 16:38:24] .../vim/lsp/rpc.lua:734	"rpc"	"/home/{me}/.local/share/nvim/mason/bin/efm-langserver"	"stderr"	"2023/10/06 16:38:24  --color Never   -: sh: 1: --color: not found\n\n"
```

After debugging for a bit I realized the empty string `""` was being returned instead of the location of stylua. Is there any additional information I can provide to help?

**Comment by Anthony-Fiddes** [comment]
Hrmm actually I have no clue now. Now it's happening with sql-formatter, but I'm not sure that I changed anything. I can see the mason/bin when I do ":echo $PATH". Maybe I messed something up. I'll keep looking into it when I can, but for now I'll just install formatters I need globally as well.

**Comment by creativenull** [comment]
Yeah I'm not sure why you are not able to get it working.

Make sure you have mason setup before you call efm setup.

Mason works for me without any issues, here is a video of it. (The classic works on my machine lol)


https://github.com/creativenull/efmls-configs-nvim/assets/3767728/666f2608-761b-4145-b511-f809516a633f

**Comment by creativenull** [comment]
Closing this as it's not related to efmls-configs issue.

**Comment by Anthony-Fiddes** [comment]
Thank you so much for the tip! I needed to move up my setup() call to mason. Maybe we should add a note in the readme that in order to find Mason executables, mason must be setup? Maybe that's obvious to others?

**Comment by Anthony-Fiddes** [comment]
In any case, thanks so much for taking the time to hear me out!

**Comment by creativenull** [comment]
This is already documented in the mason-lspconfig plugin. But it wouldn't hurt to put a note on the troubleshooting section here.

**Comment by creativenull** [comment]
Added 4339a27f1a5cc47b17a9d8467bb9b3dacc91a2f7

**Comment by Anthony-Fiddes** [comment]
Thanks, I appreciate it! :D
