### ISSUE TITLE
Adopt formatter/linter commands from dead `null-ls`

### ISSUE THREAD

**Issue by hinell** [creativenull/efmls-configs-nvim#98]
Hi. 

`null-ls` is similar to `efmls` but it got archive recently. I suggest to borrow some commands from their list of configs, see: [BUILTINS](https://github.com/nvimtools/none-ls.nvim/blob/main/doc/BUILTINS.md)

My best!

**Comment by creativenull** [comment]
I'm not sure I understand, what do you mean by commands?

**Comment by hinell** [comment]
@creativenull efm-ls takes as input `tools` that define commands to run. `null-ls` does the same, but in a bit different way. Worth to use as reference.

**Comment by creativenull** [comment]
Oh I see, well this has been the main goal of efmls-configs (adding tools that other plugins such as null-ls provides) 😅

If you don't see any tools that null-ls already provides then PRs are always.
